AWSTemplateFormatVersion: '2010-09-09'
Description: Provision HTTP API and Lambda to send emails

Parameters:
  Email:
    Type: String
    Description: Email (this will be the email with which the mails will be sent, and the sender's email will appear in the subject)
  EmailPass:
    Type: String
    Description: Password or email API key
  AllowedOrigins:
    Type: CommaDelimitedList
    Default: "https://guitarras-domingo-fernandez.es,https://www.guitarras-domingo-fernandez.es,http://guitarras-domingo-fernandez.s3-website.eu-south-2.amazonaws.com"
    Description: Allowed domains for CORS

Resources:
  EmailLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  EmailLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: EmailLambda
      Handler: index.handler
      Runtime: nodejs22.x
      Role: !GetAtt EmailLambdaRole.Arn
      Code:
        ZipFile: |
          const AWS = require("aws-sdk");
          const ses = new AWS.SES();

          // In-memory map for rate limiting
          const rateLimitMap = new Map();

          // Rate limiting configuration
          const RATE_LIMIT_WINDOW = 60 * 1000; // 60 segundos
          const MAX_REQUESTS = 5;

          const allowedOrigins = process.env.ALLOWED_ORIGINS?.split(",") || [];

          exports.handler = async (event) => {
            try {
              // --- Normalize body
              let data;
              if (typeof event.body === "string") {
                data = JSON.parse(event.body);
              } else {
                data = event.body || event;
              }

              const { name, email, subject, message, origin } = data;

              // --- CORS validation
              const normalizeOrigin = (url) => url.replace(/\/+$/, ""); // quita barras al final
              if (!origin || !allowedOrigins.some(o => normalizeOrigin(o) === normalizeOrigin(origin))) {
                return { statusCode: 403, body: JSON.stringify({ message: "Not allowed by CORS" }) };
              }

              // --- rate limiting by IP
              const ip = (event.headers && (event.headers["x-forwarded-for"] || event.headers["x-real-ip"])) || "unknown";
              const now = Date.now();
              const rateData = rateLimitMap.get(ip) || { count: 0, lastRequest: now };

              if (now - rateData.lastRequest > RATE_LIMIT_WINDOW) {
                rateData.count = 0;
                rateData.lastRequest = now;
              }
              rateData.count++;
              rateData.lastRequest = now;
              rateLimitMap.set(ip, rateData);

              if (rateData.count > MAX_REQUESTS) {
                return { statusCode: 429, body: JSON.stringify({ message: "Rate limit exceeded" }) };
              }

              // --- Basic field validation
              if (!name || !email || !subject || !message) {
                return { statusCode: 400, body: JSON.stringify({ message: "Faltan campos obligatorios" }) };
              }

              // --- Send email using SES
              await ses.sendEmail({
                Source: process.env.EMAIL_USER, 
                Destination: { ToAddresses: ["ferfdezdelcerro@outlook.com"] },
                Message: {
                  Subject: { Data: subject },
                  Body: {
                    Text: { Data: `De: ${name} (${email})\n\n${message}` },
                    Html: { Data: `<p><strong>De:</strong> ${name} (${email})</p><p>${message}</p>` }
                  }
                }
              }).promise();

              return { statusCode: 200, body: JSON.stringify({ message: "Email sent" }) };
            } catch (error) {
              console.error("Error sending email:", error);
              return { statusCode: 500, body: JSON.stringify({ message: "Error sending email", error: error.message }) };
            }
          };
      Environment:
        Variables:
          EMAIL_USER: !Ref Email
          EMAIL_PASS: !Ref EmailPass
          ALLOWED_ORIGINS: !Join [ ",", !Ref AllowedOrigins ]

  ContactApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ContactAPI
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins: !Ref AllowedOrigins
        AllowHeaders:
          - content-type
        AllowMethods:
          - POST
          - OPTIONS
        AllowCredentials: false
        MaxAge: 0

  PostIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ContactApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EmailLambda.Arn}/invocations
      PayloadFormatVersion: "2.0"

  PostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ContactApi
      RouteKey: "POST /contact"
      Target: !Sub integrations/${PostIntegration}

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ContactApi
      StageName: prod
      AutoDeploy: true

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EmailLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ContactApi}/*/POST/contact

Outputs:
  ContactApiUrl:
    Description: URL of POST endpoint /contact
    Value: !Sub "https://${ContactApi}.execute-api.${AWS::Region}.amazonaws.com/prod/contact"