Parameters:
  BucketNameParam:
    Type: String
    Description: "Bucket S3 name"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParam
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false  # MUST BE FALSE IN ORDER TO BE ABLE TO MODIFY THE POLICY!
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForWebsite
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${BucketNameParam}/*"
          - Sid: DenyAllPublicModifications
            Effect: Deny
            NotPrincipal:
              AWS: "arn:aws:iam::800425446766:root"
            Action:
              - "s3:DeleteObject"
              - "s3:DeleteObjectVersion"
              - "s3:PutLifecycleConfiguration"
            Resource: 
              - "arn:aws:s3:::${BucketNameParam}"
              - "arn:aws:s3:::${BucketNameParam}/*"